### ISSUE TITLE
Change Text to Html

### ISSUE THREAD

**Issue by mtnshadid** [claviska/jquery-alertable#10]
Suggest you change .text into .html in .alertable-prompt since i want to display a message that is spited into multiple lines and .text does not support <br> nor \r\n

.find(".alertable-prompt").text=> .find(".alertable-prompt").html

I have perform the text and i have not faced any issue since yesterday

**Comment by claviska** [comment]
You can set `options.html` to true to enable HTML. Just make sure you're sanitizing any user input to prevent XSS.

```js
$.alertable.alert('First Line<br>Second Line', {
  html: true
});
```
