### ISSUE TITLE
Wrong okButton example code

### ISSUE THREAD

**Issue by daitam** [claviska/jquery-alertable#6]
Example code for `okButton` property is
`<button class="alertable-ok" type="button">OK</button>`
type should be submit, otherwise it won't submit data
`<button class="alertable-ok" type="submit">OK</button>`

**Comment by claviska** [comment]
Good catch. Interested in submitted a PR?

**Comment by q2apro** [comment]
Found the same problem!

Readme fix above.

**Comment by claviska** [comment]
Fixed in #11.
