### ISSUE TITLE
Bootstrap Issue

### ISSUE THREAD

**Issue by CaffeineLab** [claviska/jquery-alertable#8]
Jquery 2.2.4 and bootstrap 3.3.7

Tried implementing 

```js
$('.scheduleDelete').on('click', function( ) {
    $.alertable.alert('Howdy!').always(function() {
        console.log('Alert dismissed');
      });
});
```

Any time I click my delete button the alert shows for a brief flash but doesn't allow me to click anything (not modal) and then the click event continues on.

Just hoping someone else knows the simple thing I am missing.

**Comment by claviska** [comment]
Try `event.preventDefault()`:

```js
$('.scheduleDelete').on('click', function(event) {
    event.preventDefault();
    $.alertable.alert('Howdy!').always(function() {
        console.log('Alert dismissed');
    });
});
```
